### ISSUE TITLE
[Feat]검색탭에서 '최근 본 제품' 섹션을 구현합니다.

### ISSUE THREAD

**Issue by Somin-DS** [SnoopClass/Murphy_Student_IKEA#5]
## 💡 Issue
검색탭에서 '최근 본 제품' 부분을 구현합니다.
<img width="328" alt="스크린샷 2022-10-04 오후 4 58 45" src="https://user-images.githubusercontent.com/69718283/193766085-e24cd89d-fc69-4b49-8e16-0d45f5b506b7.png">

## ✅  Todo
- [ ] UI
- [ ] 최근 본 제품 목업데이터 셋팅
- [ ] 모두 삭제 버튼 구현
- [ ] 최근 본 제품이 없을 경우 숨기기
